name: Test Oryx Dockerfile

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        app:
          - azureFunctionsApps/DotNetCore_HttpTriggerV3Sample
          - azureFunctionsApps/Node_HttpTriggerSample
          - azureFunctionsApps/Python_HttpTriggerSample
          - DotNetCore/Net5BlazorWasmClientApp
          - DotNetCore/Net5MvcApp
          - DotNetCore/NetCore6BlazorWasmApp
          - DotNetCore/NetCore6PreviewMvcApp
          - DotNetCore/NetCore7PreviewMvcApp
          - DotNetCore/NetCoreApp30.MvcApp
          - DotNetCore/NetCoreApp31.MvcApp
          - nodejs/angular6app
          - nodejs/angular8app
          - nodejs/helloworld-nuxtjs
          - nodejs/monorepo-lerna-npm
          - nodejs/nextjs-yarn2-example
          - nodejs/node-mssql
          - nodejs/node-postgres
          - nodejs/vuepress
          - nodejs/webfrontend-yarnlock
          - python/django-app
          - python/flask-app
          - python/http-server-py
          - python/mssqlserver-sample
          - python/postgres-sample
          - python/shapely-flask-app

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx
      
      - name: Build application
        run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app cormtestacr.azurecr.io/oryx/cli:latest oryx build /app
